export const defaultMovie = {
  adult: false,
  backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
  belongs_to_collection: null,
  budget: 165000000,
  genres: [
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 18,
      name: 'Drama',
    },
    {
      id: 878,
      name: 'Science Fiction',
    },
  ],
  homepage: 'http://www.interstellarmovie.net/',
  id: 157336,
  imdb_id: 'tt0816692',
  original_language: 'en',
  original_title: 'Interstellar',
  overview:
    'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  popularity: 88.047,
  poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  production_companies: [
    {
      id: 923,
      logo_path: '/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png',
      name: 'Legendary Pictures',
      origin_country: 'US',
    },
    {
      id: 9996,
      logo_path: '/3tvBqYsBhxWeHlu62SIJ1el93O7.png',
      name: 'Syncopy',
      origin_country: 'GB',
    },
    {
      id: 13769,
      logo_path: null,
      name: 'Lynda Obst Productions',
      origin_country: '',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'GB',
      name: 'United Kingdom',
    },
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2014-11-05',
  revenue: 675120017,
  runtime: 169,
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: 'Mankind was born on Earth. It was never meant to die here.',
  title: 'Interstellar',
  video: false,
  vote_average: 8.3,
  vote_count: 24306,
  videos: {
    results: [
      {
        id: '5794fffbc3a36829ab00056f',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: '2LqzF5WauAw',
        name: 'Interstellar Movie - Official Trailer',
        site: 'YouTube',
        size: 1080,
        type: 'Trailer',
      },
      {
        id: '57817b0fc3a368592500394d',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: 'LY19rHKAaAg',
        name: 'Interstellar – Trailer 4 – Official Warner Bros.',
        site: 'YouTube',
        size: 1080,
        type: 'Trailer',
      },
      {
        id: '57817ab4c3a36813870024b7',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: 'KlyknsTJk0w',
        name: 'INTERSTELLAR - Own it TODAY on Blu-ray and DIGITAL HD!',
        site: 'YouTube',
        size: 1080,
        type: 'Teaser',
      },
      {
        id: '57817ada9251417c28000b02',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: '827FNDpQWrQ',
        name: 'Interstellar - Teaser Trailer - Official Warner Bros. UK',
        site: 'YouTube',
        size: 1080,
        type: 'Trailer',
      },
      {
        id: '57817accc3a368592500392e',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: '0vxOhd4qlnA',
        name: 'Interstellar Movie - Official Trailer 3',
        site: 'YouTube',
        size: 1080,
        type: 'Trailer',
      },
      {
        id: '57817aa69251417bfc000a58',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: 'zSWdZVtXT7E',
        name: 'Interstellar - Trailer - Official Warner Bros. UK',
        site: 'YouTube',
        size: 1080,
        type: 'Trailer',
      },
      {
        id: '57817a91c3a36873ea000adf',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: 'nyc6RJEEe0U',
        name: 'Interstellar Movie - Official Teaser',
        site: 'YouTube',
        size: 1080,
        type: 'Trailer',
      },
      {
        id: '5795006f92514142390035ae',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: 'Rt2LHkSwdPQ',
        name: 'Interstellar Movie - Official Trailer 2',
        site: 'YouTube',
        size: 1080,
        type: 'Trailer',
      },
      {
        id: '5add84850e0a2608d8009256',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: 'ePbKGoIGAXY',
        name: 'Interstellar – Trailer 3 – Official Warner Bros.',
        site: 'YouTube',
        size: 1080,
        type: 'Trailer',
      },
      {
        id: '5db465f6f056d500180e96ff',
        iso_639_1: 'en',
        iso_3166_1: 'US',
        key: 'MfGfZwQ_qaY',
        name: 'Interstellar – Building A Black Hole – Official Warner Bros.',
        site: 'YouTube',
        size: 1080,
        type: 'Featurette',
      },
    ],
  },
}
